name: Android CI - Build & Trigger QA

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Permisos para ejecutar gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - name: Build APK Debug
        run: |
          ./gradlew assembleDebug

      - name: Verificar APK
        run: |
          ls -lh app/build/outputs/apk/debug/

      - name: Subir APK como artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Disparar pruebas QA (Repo Tests)
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_LOGINAPP_TESTS }}" \
            https://api.github.com/repos/dmelchor24/loginAppKtolin-tests/dispatches \
            -d '{
              "event_type": "run-mobile-tests",
              "client_payload": {
                "apk_name": "app-debug.apk",
                "branch": "${{ github.ref_name }}",
                "commit": "${{ github.sha }}"
              }
            }'
